# -*- coding: utf-8 -*-
"""Salaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bZr1P6F3FmzGibcSZZIcMhL3zRdSYSI
"""

import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')

df.head()

df.shape

df.columns

df.isna()

df.tail()

df.drop

df.head

df.dropna()

cleand_df = df.dropna()
cleand_df.tail()

cleand_df["Undergraduate Major"].loc[43]

cleand_df.loc[43]

# What college major has the highest mid-career salary? 
#How much do graduates with this major earn? (Mid-career is defined as 
#having 10+ years of experience).


max_mid_career = cleand_df["Mid-Career Median Salary"].idxmax()
cleand_df.loc[max_mid_career]

#Which college major has the lowest starting salary and how
# much do graduates earn after university?
min_salary_major = cleand_df["Starting Median Salary"].idxmin()
cleand_df.loc[min_salary_major]

#Which college major has the lowest mid-career salary and how much 
#can people expect to earn with this degree? 

min_mid_career = cleand_df["Mid-Career Median Salary"].idxmin()
cleand_df.loc[min_salary_major]

spread_col = cleand_df['Mid-Career 90th Percentile Salary'] - cleand_df['Mid-Career 10th Percentile Salary']
cleand_df.insert(1, "Spread", spread_col)
cleand_df.head()

low_risk = cleand_df.sort_values("Spread")
low_risk[["Spread", "Undergraduate Major"]].head()

#Using the .sort_values() method, can you find the degrees with the highest 
#potential? Find the top 5 degrees with the highest values in the 90th percentile. 

potential_majors = cleand_df.sort_values("Mid-Career 90th Percentile Salary", ascending=False)
potential_majors.head()

#Also, find the degrees with the greatest spread in salaries.
#Which majors have the largest difference between high and 
#low earners after graduation.
high_risk = cleand_df.sort_values("Spread", ascending=False)
cleand_df[["Spread", "Undergraduate Major"]].head()

cleand_df.groupby("Group").count()

cleand_df.groupby("Group").mean().sort_values("Starting Median Salary")

pd.options.display.float_format = '{:,.2f}'.format 
cleand_df.groupby("Group").mean().sort_values("Starting Median Salary")